# Enable colors and change prompt:
autoload -U colors && colors

# Load version control information
autoload -Uz vcs_info
DISABLE_AUTO_TITLE="true"

precmd () {
  vcs_info
  window_title="\033]0;$(pwd -L)\007"
  echo -ne "$window_title"
}

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '(%b)'

# Set up the prompt (with git branch name)
setopt PROMPT_SUBST

# Enable colored output
export CLICOLOR=YES 
if which dircolors &>/dev/null; then
  alias ls="ls --color=auto"
  alias diff='diff --color=auto'
  alias grep='grep --color=auto'
fi

# zsh-autosuggestions enables fish-like
#source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# syntax highlighting
#source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=cyan,underline
#ZSH_HIGHLIGHT_STYLES[precommand]=fg=cyan,underline
#ZSH_HIGHLIGHT_STYLES[arg0]=fg=cyan
#ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
#ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# Share history between tmux windows
setopt SHARE_HISTORY
setopt hist_ignore_space
setopt histignoredups

# Support TAB/TAB/TAB for repeated autocompletion
zmodload zsh/complist
bindkey -M menuselect '^I' accept-and-infer-next-history

# history completion menu Ctrl+X+X
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^X^X' history-beginning-search-menu

# fix keys home/end/delete, command: autoload zkbd ; zkbd
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[4~"  end-of-line
bindkey  "^[[3~"  delete-char
bindkey  "^?"     backward-delete-char


# No color
# PROMPT='%n@%m ${PWD/#$HOME/~} ${vcs_info_msg_0_}> '

# Color
NEWLINE=$'\n'
PROMPT='%{$fg[gray]%}%n%{$fg[gray]%}@%{$fg[gray]%}%m%{$fg[cyan]%} ${PWD/#$HOME/~} %{$fg[green]%}${vcs_info_msg_0_}%{$reset_color%}${NEWLINE}% %#%{$fg[default]%} '

# Add RVM to PATH for scripting. 
export PATH="$PATH:$HOME/.rvm/bin"
source $HOME/.rvm/scripts/rvm

